### ISSUE TITLE
Detected as trojan

### ISSUE THREAD

**Issue by MatthieuTinnes** [Eperty123/Steam-Manifest-Creator#2]
https://www.virustotal.com/fr/file/d2a4641190f7a7d3400dc554ec981ef97fc8e06158fb44b313a1241a67e897e6/analysis/1525559288/
![image](https://user-images.githubusercontent.com/18295583/39668083-95dc75a0-50c4-11e8-9cae-ad4057193da7.png)

**Comment by Eperty123** [comment]
I packed the executable because it contained some sensitive information as it connected a database. With my limited knowledge back then, that was my only solution as GitHub was different at the time.

PS. Yes it's a late reply but better late than never.

**Comment by MatthieuTinnes** [comment]
Thanks for the reply, wasn't expected to get one
